language: node_js
node_js:
  - node 

script:
  - |
    if [ -n $B64_FIREBASE_TOKEN ]; then
      npm install -g firebase-tools
      TOKEN="$(echo -n $B64_FIREBASE_TOKEN | base64 -d)"
      firebase deploy --token $TOKEN --project "dragon6-224813"
    fi
branches:
  only:
    - master
