language: node_js
node_js:
  - node 

before_script:
  - npm install -g firebase-tools
script:
  - |
    if [ $TRAVIS_PULL_REQUEST == "false" && $TRAVIS_REPO_SLUG = "dragonfruitnetwork/Dragon6-Assets"]; then
      TOKEN="$(echo -n $B64_FIREBASE_TOKEN | base64 -d)"
      firebase deploy --token $TOKEN --project "dragon6-224813"
    fi
branches:
  only:
    - master
