language: node_js
node_js:
  - node 

stages:
  - name: deploy
    if: type = push AND fork = false AND env(B64_FIREBASE_TOKEN) IS present

jobs:
  include: 
  - stage: deploy
    name: "Firebase Deploy"
    script:
      - npm install -g firebase-tools
      - TOKEN="$(echo -n $B64_FIREBASE_TOKEN | base64 -d)"
      - firebase deploy --token $TOKEN --project "dragon6-224813"
    if: branch = master
