language: node_js
before_script:
  - npm install -g firebase-tools
script:
  - TOKEN="$(echo -n $B64_FIREBASE_TOKEN | base64 -d)"
  - firebase deploy --token $TOKEN --project "dragon6-224813"
branches:
  only:
  - master
